creation_rules:
  - age:
      # David Douglas
      - age1902gh5rcwtq3u7c6548rr9lhss3xxp65mu0nk4u6fl6untmqrppsl26rqr
      # Handoff maintainer (generated 2026-07-19)
      - age19s0002vzzd2qxez2l2uvy3095auzn27j29ef367sqsgpz2yzpdtstgckzs
