tigris_access_key: ENC[AES256_GCM,data:11SETni6hTH0pgcxi3qacAg117hL8ewXNnEPmnRlkyduMwjRA6uQMWhFHStT2RntKPJTd983,iv:u7BwmDQHvcxRWD6xlxC3prEujRhAYfvl9gVIREhrVwk=,tag:l88vZ75UcO4TvSPlrvracw==,type:str]
tigris_secret_key: ENC[AES256_GCM,data:4iNG7Lp1o2NCcPiSFzf//4eAl6LlMijhE8aUnA166JWE7LXqAO6ZIcWMrR4W3eiYPp9hxhC/iIOp6xKQGniM35njj2nEMLVAIGvH,iv:JDodkjFHXPaN6bSYG3ZNZrmYLYg7KcSLQ4fmfkNGFzs=,tag:BkAhv18xl/QXIvz4X0uomQ==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:/Asy6tApd89UmrejnMtuybGZWt7mfNAWw1GlMpDS2XxuCJ0y+5crb0r28cmdPtyQbF0keC0LTgUuCKVIhGiNhA==,iv:492O7iohqra+9U/9/TXwYe27V/ElM3WXumNI+cZATWM=,tag:Stj1rUYO6suentnyKpPRSg==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:p7sCqPxqPkcv7vjMH6L2phaFiGK+y1gTkBYpP1+Fdux1T3QfdXIpO5hiqJhxwSc+fnWsy2U=,iv:cBpxwdb36nVmZfpVBmKuJH6Hkyeywd+XpyqFw7rqvwU=,tag:ThedvVxh0yFK3w1+8OcpBQ==,type:str]
#ENC[AES256_GCM,data:yYf5ySiFagl9xedew/UE65bQBCO2cIdf7Q==,iv:YgAcztlJmxCwScgjLRxax15WGova8Gzy028Tnw35q+w=,tag:8qdd5GqVvVObW983jHSxkA==,type:comment]
github_personal_access_token: ENC[AES256_GCM,data:2GABTWrqEpj7i0iHKcXzuOFndxh282inKt1smBp7f3QE720Hmkq5mQ==,iv:pGp8cjqmcbauv8By4ZpI4YYNycUGbjd3U7YHlrZeKws=,tag:oqyMH64qAqimJkcH9kVJEw==,type:str]
render_api_key: ENC[AES256_GCM,data:GA44FtAGaqMdxSuTlOz0A10mGra3e0/RMJ6bTjz9WYs=,iv:rR/mX+2RzQDVrmeWg2GHHnbUiK9oHgXBBaXjkq7h5b4=,tag:xp088xu4weCwSJcaAAIufA==,type:str]
sops:
    age:
        - recipient: age1902gh5rcwtq3u7c6548rr9lhss3xxp65mu0nk4u6fl6untmqrppsl26rqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcHNPU2IrZEJ4MkdHN0Fu
            eVNYVVZmZk8wVEwxMlczZ2EzZTdpcVZlMlVvCjZ6YUw3V1FpakY5Q2lyTnlNaEtY
            anF2bit4WFhhdFlVclVqU21wLzZwdUkKLS0tIGduSnpzNGxwcTZuQm5iM0lQWXlC
            YW9HMzdMalByeEQ5RGhOWmdMR095bWMKc/a1nYcV53EpZBfMfLs7mmdKuZV2uaFB
            3uYRasgIiEUKrOp5XdPGLnt5ovIVY4mUtXUP3xzYnAcI1gdbrTuHQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T19:20:43Z"
    mac: ENC[AES256_GCM,data:+qn0VVD9N1Ar/BYKFBMxVmuU7PjjdnCmu2IsIdXWwkyhbZE2D8S78Ng9QbiR+ehnKSw9NL9sjsVnfI/P0pfxb/o88LBSCmrfiewdyjNbSho5tVWkOW53CMep8QXOuwjiEGDSMfSzNCoIqxEnSQoX4lm7L3ZHyRCBWF7bCdIi4i4=,iv:gk/ik01bukcyld+6x/I/diM+ZGxSgRg3k1ue0kx2+yI=,tag:kvKoGC9+sHk3HCUnTIY1YA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
