COOKIE_HASH_KEY: j847UxOgRA2Pjd+yq61MR/Y6sss5J6lEnPbX+7Zfuts=
COOKIE_BLOCK_KEY: zuCTo0QP57BTWzIyIhpgi/yM1b17GWF/1/dkU8PKk7w=
DATABASE_URL: postgresql://postgres.nxlrzbwgszefyqfnmpim:g2rC9DWw3KZi2dRr4qYZ97Sp@aws-1-us-east-1.pooler.supabase.com:5432/postgres
S3_BUCKET_NAME: christjesus-documents-development
STRIPE_PUBLISHABLE_KEY: pk_test_51T6jBsBSKFXP30w7lwisIxy4vT3X6dUrQUK16QMOkuw3CMnYnlCQ9rfpseHnKGmGFLW28orhC1cnwSpq5IQOSEnM00RRljwxQo
STRIPE_SECRET_KEY: sk_test_51T6jBsBSKFXP30w71DmME4NL8SW0tgWYKDdPFN3Sr1f0org9voi3JW3vg0R4QnFD41FEvWYIJwpKpugRTQ2PNzhT007KrcRl4l
STRIPE_WEBHOOK_SECRET: whsec_2d736121ce1b42fb809787bfcb4ce6d35633c79f58dd57e634f287f597060caa
AUTH0_CLIENT_ID: QYcMdOYZ32V4W5OI0gEnizS9lF4WYJvp
AUTH0_CLIENT_SECRET: vfZXbi7-2371jKmNtqjywRJP9vXeTHnFWIxU9cOAA7Q0El1SpHKqgFftmupZbMZN
AUTH0_DOMAIN: christjesus-development.us.auth0.com
AUTH0_CALLBACK_URL: http://localhost:8080/auth/callback
AUTH0_LOGOUT_URL: http://localhost:8080/
AUTH0_MGMT_CLIENT_ID: WzhNToXkTKYyduzFluHm96rH6a5bvN99
AUTH0_MGMT_CLIENT_SECRET: Nx0mmW_FT3ZqaAHWklb0p1MM2XNB2GJeIN-eHJQLY-PJZ5dRG5nXwUE2GrJ5KK5r
TIGRIS_ACCESS_KEY: tid_bByUoyMFkZft_ySSVwTUUqIJFjftHMtMqOoORGflVItcTVCInV
TIGRIS_SECRET_KEY: tsec_flh31YVzfvlDcNPk1Q363qYGDgz4bASum5rJNBhMocevr57hlS4oPtVyPVLVc9lZkfh_A4
USPS_CONSUMER_KEY: fZHsCr162yCLOOF2LHlA4kpKB8l7Su692LCiNciSnvvQGQIt
USPS_CONSUMER_SECRET: qeWcTD80VzRRs73J2FxbEEMlvmaRktBIlsAOEFqKVX9JSOymZWDgH3tJEy5woW6H
RESEND_API_KEY: re_FuDLSvXr_9RnGseUFRC4FSJby3sE6tnYg
RESEND_WEBHOOK_SECRET: whsec_4Q75uUjDU3ZTWYvVryK09+UezaCgit4h
EMAIL_FROM_ADDRESS: hello@cja.onetwentyseven.dev
NGROK_AUTHTOKEN: 1Xs29ugNKfKsNf4QP5rpoRf6A0M_7fKnuhV2GtrJouWue2EQQ
NGROK_API_KEY: 3BfnHmilB03ElVZleleetMNytp7_7FB6fa2s7gRtMSTbX4W9R
