package main

import (
	"christjesus/internal/db"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli/v2"
)

type testAccountsFile struct {
	Accounts map[string]struct {
		Email  string `json:"email"`
		UserID string `json:"userId"`
	} `json:"accounts"`
}

var e2eResetCommand = &cli.Command{
	Name:  "e2e-reset",
	Usage: "Reset database state for E2E test users (deletes needs, clears user_type)",
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:  "accounts-file",
			Value: "e2e/test-accounts.json",
			Usage: "Path to the test-accounts.json file generated by Terraform",
		},
	},
	Action: func(c *cli.Context) error {
		cfg, err := loadConfig()
		if err != nil {
			return fmt.Errorf("failed to load config: %w", err)
		}

		accountsPath := c.String("accounts-file")
		if !filepath.IsAbs(accountsPath) {
			wd, _ := os.Getwd()
			accountsPath = filepath.Join(wd, accountsPath)
		}

		data, err := os.ReadFile(accountsPath)
		if err != nil {
			return fmt.Errorf("failed to read accounts file %s: %w", accountsPath, err)
		}

		var accounts testAccountsFile
		if err := json.Unmarshal(data, &accounts); err != nil {
			return fmt.Errorf("failed to parse accounts file: %w", err)
		}

		ctx := context.Background()
		pool, err := db.Connect(ctx, cfg)
		if err != nil {
			return fmt.Errorf("failed to connect to database: %w", err)
		}
		defer pool.Close()

		// Collect auth subjects (e.g. "auth0|abc123") from the accounts file
		var authSubjects []string
		for _, acct := range accounts.Accounts {
			authSubjects = append(authSubjects, acct.UserID)
		}

		if len(authSubjects) == 0 {
			logrus.Warn("No test accounts found in accounts file")
			return nil
		}

		// Find user IDs by auth_subject
		rows, err := pool.Query(ctx,
			`SELECT id FROM christjesus.users WHERE auth_subject = ANY($1)`,
			authSubjects,
		)
		if err != nil {
			return fmt.Errorf("failed to query test users: %w", err)
		}
		defer rows.Close()

		var userIDs []string
		for rows.Next() {
			var id string
			if err := rows.Scan(&id); err != nil {
				return fmt.Errorf("failed to scan user id: %w", err)
			}
			userIDs = append(userIDs, id)
		}

		if len(userIDs) == 0 {
			logrus.Info("No test users found in database, nothing to reset")
			return nil
		}

		logrus.WithField("user_ids", userIDs).Info("Resetting E2E test users")

		// Delete needs (cascades to stories, assignments, documents, progress events, etc.)
		result, err := pool.Exec(ctx,
			`DELETE FROM christjesus.needs WHERE user_id = ANY($1)`,
			userIDs,
		)
		if err != nil {
			return fmt.Errorf("failed to delete needs: %w", err)
		}
		logrus.WithField("deleted", result.RowsAffected()).Info("Deleted needs")

		// Delete addresses
		result, err = pool.Exec(ctx,
			`DELETE FROM christjesus.user_addresses WHERE user_id = ANY($1)`,
			userIDs,
		)
		if err != nil {
			return fmt.Errorf("failed to delete addresses: %w", err)
		}
		logrus.WithField("deleted", result.RowsAffected()).Info("Deleted addresses")

		// Delete donor preferences
		result, err = pool.Exec(ctx,
			`DELETE FROM christjesus.donor_preferences WHERE user_id = ANY($1)`,
			userIDs,
		)
		if err != nil {
			return fmt.Errorf("failed to delete donor preferences: %w", err)
		}
		logrus.WithField("deleted", result.RowsAffected()).Info("Deleted donor preferences")

		// Reset user_type so onboarding starts fresh
		result, err = pool.Exec(ctx,
			`UPDATE christjesus.users SET user_type = NULL WHERE id = ANY($1)`,
			userIDs,
		)
		if err != nil {
			return fmt.Errorf("failed to reset user_type: %w", err)
		}
		logrus.WithField("updated", result.RowsAffected()).Info("Reset user_type to NULL")

		logrus.Info("E2E reset complete")
		return nil
	},
}
